/**
 * RFC 5545 Compliant iCalendar (.ics) Generator
 *
 * Requirements met:
 * - Proper VCALENDAR wrapper, VERSION:2.0, PRODID, CALSCALE:GREGORIAN, METHOD:PUBLISH
 * - Stable event UIDs
 * - DTSTAMP in UTC
 * - Correctly escaped characters: '\\', ';', ',', '\n'
 * - CRLF (\r\n) line terminators
 * - UTF-8-safe line folding strictly at <= 75 octets (bytes)
 * - Timed events with UTC timestamps ending in 'Z'
 * - Daily summaries as DATE-based all-day events with exclusive next-day DTEND
 * - Consumes the shared AstroRecord dataset directly
 */

import { AstroRecord } from '../types';

/**
 * Formats a Date to iCalendar UTC string: YYYYMMDDTHHMMSSZ
 */
export function formatIcsUtc(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  const h = String(date.getUTCHours()).padStart(2, '0');
  const min = String(date.getUTCMinutes()).padStart(2, '0');
  const s = String(date.getUTCSeconds()).padStart(2, '0');
  return `${y}${m}${d}T${h}${min}${s}Z`;
}

/**
 * Formats a local date string YYYY-MM-DD into iCalendar DATE format: YYYYMMDD
 */
export function formatIcsDate(dateString: string): string {
  return dateString.replace(/-/g, '');
}

/**
 * Computes the next calendar day string (YYYYMMDD) for exclusive all-day DTEND.
 */
export function getNextIcsDate(dateString: string): string {
  const [y, m, d] = dateString.split('-').map(Number);
  const nextDate = new Date(Date.UTC(y, m - 1, d + 1));
  const ny = nextDate.getUTCFullYear();
  const nm = String(nextDate.getUTCMonth() + 1).padStart(2, '0');
  const nd = String(nextDate.getUTCDate()).padStart(2, '0');
  return `${ny}${nm}${nd}`;
}

/**
 * Escapes text according to RFC 5545 section 3.3.11:
 * - Backslash (\) -> \\
 * - Semicolon (;) -> \;
 * - Comma (,) -> \,
 * - Newline (\n) -> \n
 */
export function escapeIcsText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/**
 * Folds lines longer than 75 octets (bytes) per RFC 5545 section 3.1.
 * Ensures UTF-8 byte counting so multi-byte Unicode characters (emojis, etc.)
 * are not sliced mid-codepoint.
 */
export function foldLineUtf8(line: string, maxOctets = 75): string {
  const encoder = new TextEncoder();
  const rawBytes = encoder.encode(line);
  if (rawBytes.length <= maxOctets) {
    return line;
  }

  const chars = Array.from(line); // Clean Unicode grapheme/codepoint split
  const lines: string[] = [];
  let currentLine = '';
  let currentOctets = 0;
  let isFirstLine = true;

  for (const ch of chars) {
    const chOctets = encoder.encode(ch).length;
    const limit = isFirstLine ? maxOctets : maxOctets - 1; // 1 byte reserved for leading space on folded lines

    if (currentOctets + chOctets > limit) {
      lines.push(currentLine);
      currentLine = ch;
      currentOctets = chOctets;
      isFirstLine = false;
    } else {
      currentLine += ch;
      currentOctets += chOctets;
    }
  }

  if (currentLine) {
    lines.push(currentLine);
  }

  return lines.join('\r\n ');
}

/**
 * Generates an RFC 5545 compliant .ics payload from filtered AstroRecords.
 */
export function generateIcsPayload(
  records: AstroRecord[],
  calendarName = 'AstroMoon Calendar',
  timeZone = 'UTC'
): string {
  const dtstamp = formatIcsUtc(new Date());

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//AstroMoon Cal//Astrological Lunar Calendar//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    foldLineUtf8(`X-WR-CALNAME:${escapeIcsText(calendarName)}`),
    foldLineUtf8(`X-WR-TIMEZONE:${escapeIcsText(timeZone)}`),
    foldLineUtf8(
      'X-WR-CALDESC:Accurate Moon phases, zodiac sign ingresses, and astronomical alignments generated by AstroMoon Cal.'
    ),
  ];

  for (const rec of records) {
    lines.push('BEGIN:VEVENT');
    lines.push(foldLineUtf8(`UID:${rec.id}@astromooncal.app`));
    lines.push(`DTSTAMP:${dtstamp}`);

    if (rec.isAllDay) {
      // All-day event (daily summary)
      const dtstart = formatIcsDate(rec.localDateString);
      const dtend = getNextIcsDate(rec.localDateString);
      lines.push(`DTSTART;VALUE=DATE:${dtstart}`);
      lines.push(`DTEND;VALUE=DATE:${dtend}`);
    } else if (rec.utcTime) {
      // Timed event (exact ingress, quarter peak, or eclipse peak)
      const dtstart = formatIcsUtc(rec.utcTime);
      // Event block: 1 hour default duration
      const endTime = new Date(rec.utcTime.getTime() + 3600 * 1000);
      const dtend = formatIcsUtc(endTime);
      lines.push(`DTSTART:${dtstart}`);
      lines.push(`DTEND:${dtend}`);
    }

    lines.push(foldLineUtf8(`SUMMARY:${escapeIcsText(rec.title)}`));
    lines.push(foldLineUtf8(`DESCRIPTION:${escapeIcsText(rec.description)}`));
    lines.push('STATUS:CONFIRMED');
    lines.push('TRANSP:TRANSPARENT'); // Non-blocking calendar event
    lines.push('END:VEVENT');
  }

  lines.push('END:VCALENDAR');

  return lines.join('\r\n');
}

/**
 * Triggers client-side browser download of .ics calendar file.
 */
export function downloadIcsFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute(
    'download',
    filename.endsWith('.ics') ? filename : `${filename}.ics`
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
