import { ZodiacSignInfo } from '../types';

export const ZODIAC_SIGNS: ZodiacSignInfo[] = [
  {
    index: 0,
    name: 'Aries',
    symbol: '♈',
    glyph: '♈ Aries',
    element: 'Fire',
    modality: 'Cardinal',
    ruler: 'Mars',
    startDeg: 0,
    endDeg: 30,
    colorClass: 'text-rose-400 border-rose-500/30 bg-rose-500/10',
    theme: 'Action, Initiative & Courage',
    description: 'The Moon shifts into Aries. Energy focus: Action, passion, initial sparks, and competitive drive. Good day for starting projects, assertive physical movement, and pioneering initiatives.',
    activities: ['Launch bold new initiatives', 'High-intensity workouts & movement', 'Take decisive risks', 'Tackle delayed decisions'],
  },
  {
    index: 1,
    name: 'Taurus',
    symbol: '♉',
    glyph: '♉ Taurus',
    element: 'Earth',
    modality: 'Fixed',
    ruler: 'Venus',
    startDeg: 30,
    endDeg: 60,
    colorClass: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10',
    theme: 'Grounding, Sensuality & Stability',
    description: 'The Moon shifts into Taurus. Energy focus: Grounding, stability, sensory pleasure, and material patience. Good day for financial planning, culinary arts, planting seeds, and savoring nature.',
    activities: ['Review budgets and investments', 'Cook a gourmet nourishing meal', 'Gardening and nature grounding', 'Body relaxation and massage'],
  },
  {
    index: 2,
    name: 'Gemini',
    symbol: '♊',
    glyph: '♊ Gemini',
    element: 'Air',
    modality: 'Mutable',
    ruler: 'Mercury',
    startDeg: 60,
    endDeg: 90,
    colorClass: 'text-amber-300 border-amber-400/30 bg-amber-400/10',
    theme: 'Curiosity, Intellect & Networking',
    description: 'The Moon shifts into Gemini. Energy focus: Curiosity, lively communication, mental agility, and multitasking. Good day for writing, networking, reading, and exchanging fresh ideas.',
    activities: ['Brainstorming and writing', 'Connecting with friends & colleagues', 'Learning something new', 'Engaging in vibrant debates'],
  },
  {
    index: 3,
    name: 'Cancer',
    symbol: '♋',
    glyph: '♋ Cancer',
    element: 'Water',
    modality: 'Cardinal',
    ruler: 'Moon',
    startDeg: 90,
    endDeg: 120,
    colorClass: 'text-cyan-300 border-cyan-400/30 bg-cyan-400/10',
    theme: 'Nurturance, Intuition & Sanctuary',
    description: 'The Moon shifts into Cancer (domicile). Energy focus: Nurturing, emotional intuition, domestic sanctuary, and deep memories. Good day for family connection, restorative home care, and honoring gut feelings.',
    activities: ['Sanctuary nesting & home cleaning', 'Cooking comfort food for loved ones', 'Journaling emotional discoveries', 'Baths and water rituals'],
  },
  {
    index: 4,
    name: 'Leo',
    symbol: '♌',
    glyph: '♌ Leo',
    element: 'Fire',
    modality: 'Fixed',
    ruler: 'Sun',
    startDeg: 120,
    endDeg: 150,
    colorClass: 'text-yellow-400 border-yellow-500/30 bg-yellow-500/10',
    theme: 'Radiance, Creativity & Expression',
    description: 'The Moon shifts into Leo. Energy focus: Creative radiance, bold self-expression, warmth, and generous play. Good day for performance, celebratory gatherings, leadership, and heartfelt artistic creation.',
    activities: ['Express your creative voice', 'Socialize and celebrate with friends', 'Treat yourself to something special', 'Step into leadership'],
  },
  {
    index: 5,
    name: 'Virgo',
    symbol: '♍',
    glyph: '♍ Virgo',
    element: 'Earth',
    modality: 'Mutable',
    ruler: 'Mercury',
    startDeg: 150,
    endDeg: 180,
    colorClass: 'text-teal-400 border-teal-500/30 bg-teal-500/10',
    theme: 'Precision, Wellness & Service',
    description: 'The Moon shifts into Virgo. Energy focus: Precision, mindful organization, wellness routines, and thoughtful service. Good day for editing, decluttering, clean nutrition, and refining daily workflows.',
    activities: ['Declutter workspaces and digital files', 'Plan a healthy week of meals', 'Schedule wellness checkups', 'Fix bugs and optimize details'],
  },
  {
    index: 6,
    name: 'Libra',
    symbol: '♎',
    glyph: '♎ Libra',
    element: 'Air',
    modality: 'Cardinal',
    ruler: 'Venus',
    startDeg: 180,
    endDeg: 210,
    colorClass: 'text-indigo-300 border-indigo-400/30 bg-indigo-400/10',
    theme: 'Harmony, Aesthetics & Diplomacy',
    description: 'The Moon shifts into Libra. Energy focus: Harmony, aesthetic elegance, diplomatic collaboration, and balance. Good day for peaceful negotiations, romantic dates, artistic styling, and social connection.',
    activities: ['Rebalance relationships', 'Redecorate or curate spaces', 'Mediate disputes with grace', 'Enjoy a cultural date or gallery visit'],
  },
  {
    index: 7,
    name: 'Scorpio',
    symbol: '♏',
    glyph: '♏ Scorpio',
    element: 'Water',
    modality: 'Fixed',
    ruler: 'Pluto & Mars',
    startDeg: 210,
    endDeg: 240,
    colorClass: 'text-purple-400 border-purple-500/30 bg-purple-500/10',
    theme: 'Depth, Transformation & Intimacy',
    description: 'The Moon shifts into Scorpio. Energy focus: Emotional depth, intuitive transformation, intimacy, and probing mystery. Good day for research, deep psychological insight, releasing old attachments, and authentic intimacy.',
    activities: ['Deep investigative research', 'Honest, soul-level conversations', 'Let go of stagnant habits', 'Shadow work and quiet meditation'],
  },
  {
    index: 8,
    name: 'Sagittarius',
    symbol: '♐',
    glyph: '♐ Sagittarius',
    element: 'Fire',
    modality: 'Mutable',
    ruler: 'Jupiter',
    startDeg: 240,
    endDeg: 270,
    colorClass: 'text-orange-400 border-orange-500/30 bg-orange-500/10',
    theme: 'Expansion, Truth & Adventure',
    description: 'The Moon shifts into Sagittarius. Energy focus: Expansive optimism, philosophical exploration, travel yearning, and quest for truth. Good day for adventurous learning, outdoor excursions, and broad vision planning.',
    activities: ['Plan outdoor hikes and travels', 'Study philosophy or foreign cultures', 'Look at the big-picture horizon', 'Spread good humor and enthusiasm'],
  },
  {
    index: 9,
    name: 'Capricorn',
    symbol: '♑',
    glyph: '♑ Capricorn',
    element: 'Earth',
    modality: 'Cardinal',
    ruler: 'Saturn',
    startDeg: 270,
    endDeg: 300,
    colorClass: 'text-stone-300 border-stone-400/30 bg-stone-500/10',
    theme: 'Mastery, Structure & Ambition',
    description: 'The Moon shifts into Capricorn. Energy focus: Pragmatic ambition, discipline, long-term mastery, and structured milestones. Good day for career commitments, building lasting foundations, and professional focus.',
    activities: ['Outline quarterly career roadmaps', 'Exercise self-discipline and focus', 'Tackle challenging structural work', 'Honor mentorship and wisdom'],
  },
  {
    index: 10,
    name: 'Aquarius',
    symbol: '♒',
    glyph: '♒ Aquarius',
    element: 'Air',
    modality: 'Fixed',
    ruler: 'Uranus & Saturn',
    startDeg: 300,
    endDeg: 330,
    colorClass: 'text-sky-400 border-sky-500/30 bg-sky-500/10',
    theme: 'Innovation, Individuality & Community',
    description: 'The Moon shifts into Aquarius. Energy focus: Innovation, intellectual independence, community vision, and progressive thinking. Good day for brainstorming future technology, humanitarian work, and authentic nonconformity.',
    activities: ['Collaborate on community projects', 'Experiment with new technology', 'Embrace eccentric, original angles', 'Connect with kindred spirits'],
  },
  {
    index: 11,
    name: 'Pisces',
    symbol: '♓',
    glyph: '♓ Pisces',
    element: 'Water',
    modality: 'Mutable',
    ruler: 'Neptune & Jupiter',
    startDeg: 330,
    endDeg: 360,
    colorClass: 'text-violet-300 border-violet-400/30 bg-violet-400/10',
    theme: 'Compassion, Dreams & Mysticism',
    description: 'The Moon shifts into Pisces. Energy focus: Spiritual imagination, poetic empathy, boundaryless dreams, and mystical healing. Good day for meditation, music composition, sound healing, and deep creative drift.',
    activities: ['Music immersion and sound healing', 'Dream journaling and contemplation', 'Gentle breathwork and yoga', 'Offer selfless compassion to someone in need'],
  },
];

export function getZodiacSignFromLongitude(longitude: number): {
  sign: ZodiacSignInfo;
  degrees: number;
  minutes: number;
  formatted: string;
} {
  const norm = ((longitude % 360) + 360) % 360;
  const index = Math.floor(norm / 30);
  const sign = ZODIAC_SIGNS[index] || ZODIAC_SIGNS[0];
  const totalDegInSign = norm - sign.startDeg;
  const degrees = Math.floor(totalDegInSign);
  const minutes = Math.floor((totalDegInSign - degrees) * 60);
  const formatted = `${degrees}° ${minutes.toString().padStart(2, '0')}' ${sign.symbol} ${sign.name}`;

  return {
    sign,
    degrees,
    minutes,
    formatted,
  };
}
